env_name: walker_mount_reconfig
agent_specs:
  batch_design: true
# training parameters
gamma: 0.995
tau: 0.95
policy_specs:
  control_log_std: 0

robot_param_scale: 1
skel_transform_nsteps: 5

done_condition:
  max_ang: 720

obs_specs:
  attr: ['depth']
  sim: []
  design: true
  clip_qvel: true
  use_projected_params: true
  use_body_ind: true
max_body_depth: 4

add_body_condition:
  max_nchild: 3

reconfig_specs:
  reconfig: true
  intrinsic_reward_coeff: 10.0

robot:
  param_mapping: sin
  
  body_params:
    offset:
      type: 'xz'
      lb: [-0.5, -0.5]
      ub: [0.5, 0.5]

  joint_params: {}

  geom_params:
    size:
      lb: 0.03
      ub: 0.08
    ext_start:
      lb: 0.0
      ub: 0.5

  actuator_params:
    gear:
      lb: 20
      ub: 400

  
